---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Tokyo"

  # - package-ecosystem: "bundler"
  #   directory: "/ruby"
  #   schedule:
  #     interval: "daily"
  #     time: "10:00"
  #     timezone: "Asia/Tokyo"
  #   versioning-strategy: "increase"
