########################################
# Bundler Cops: Gemfile 用の設定
#   - RuboCop のデフォルト設定に従う
########################################


########################################
# Layout Cops: TODO
########################################


########################################
# Linting Cops: TODO
########################################


########################################
# Metrics Cops: TODO
########################################


########################################
# Migration Cops: TODO
########################################


########################################
# Naming Cops: TODO
########################################


########################################
# Security Cops: TODO
########################################


########################################
# Style Cops: TODO
########################################

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
