require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  # TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/*
    - config/environments/*
    - db/**/*
    - node_modules/**/*
    - vendor/**/*

########################################
# Bundler Cops: Cops for Gemfile
#   - Follow RuboCop's default style
########################################

# Bundler/DuplicatedGem
#   Enabled: true
# Bundler/GemComment
#   Enabled: false
# Bundler/InsecureProtocolSource
#   Enabled: true
# Bundler/OrderedGems
#   Enabled: true


########################################
# Layout Cops: TODO
########################################


########################################
# Linting Cops: TODO
########################################


########################################
# Metrics Cops: TODO
########################################


########################################
# Migration Cops: TODO
########################################


########################################
# Naming Cops: TODO
########################################


########################################
# Performance Cops: TODO
########################################


########################################
# Rails Cops: TODO
########################################

Rails:
  Enabled: true


########################################
# RSpec Cops: TODO
########################################


########################################
# Security Cops: TODO
########################################


########################################
# Style Cops: TODO
########################################

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
