name: Check .rubocop.yml for ruby

on:
  pull_request:
    paths:
      - .github/workflows/ruby.yaml
      - ruby/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/ruby.yaml
      - ruby/**

jobs:
  rubocop:
    name: Check .rubocop.yml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Fetch bundler cache
        uses: actions/cache@v3
        with:
          path: /usr/local/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-bundler-

      - name: Run bundle install
        run: gem install bundler && bundle install
        working-directory: ./ruby
      - name: Run Rubocop
        run: bundle exec rubocop
        working-directory: ./ruby
